name: deep-paint
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - bitsandbytes=0.43.3
  - ca-certificates
  - certifi
  - fire=0.6.0
  - hydra-core=1.3.2
  - jupyter=1.1.1
  - lightning=2.4.0
  - matplotlib=3.9.2
  - natsort=8.4.0
  - omegaconf=2.3.0
  - openssl
  - pandas=2.2.2
  - plotly=5.24.0
  - python=3.11
  - pytorch=2.4.1
  - pytorch-cuda=12.1
  - pyyaml=6.0.2
  - rich=13.7.1
  - scikit-learn=1.5.1
  - seaborn=0.13.2
  - tensorboard=2.17.1
  - tensorboardx=2.6.2.2
  - torchmetrics=1.4.0
  - torchvision=0.19.1
  - pip:
      - docstring-parser==0.16
      - jsonargparse==4.32.1
      - kaleido==0.2.1
      - typeshed-client==2.7.0